version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 400
      runas: root
    
  ApplicationStart:
    
    - location: scripts/start_app.sh
      timeout: 300
      runas: root