version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_nodejs.sh
      timeout: 300
      runas: root
    
  ApplicationStart:
    - location: scripts/install_dependencies.sh
      timeout: 400
      runas: root
    - location: scripts/start_app.sh
      timeout: 300
      runas: root