version: 0.0
os: linux
files:
  - source: /
    destination: /app
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_nodejs.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root